version: "3.9"

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest # Using the recommended image
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv
      - ENCRYPTION
    # environment:
    # ENCRYPTION: "thisis24charlongencryption" # 24 characters for AES-192
    ports:
      - "8091:8090" # Exposing port 8091 on the host machine to port 8090 in the container
    volumes:
      - ./pb_data:/pb_data # Data persistence
      - ./pb_public:/pb_public # Public files
      - ./pb_migrations:/pb_migrations # Migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pocketbase-network

networks:
  pocketbase-network:
    driver: bridge
