version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: strapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strongpassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi_net

volumes:
  postgres_data:

networks:
  strapi_net:
    driver: bridge
