/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FilmLineupImport } from './routes/film-lineup'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FilmLineupRoute = FilmLineupImport.update({
  id: '/film-lineup',
  path: '/film-lineup',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/film-lineup': {
      id: '/film-lineup'
      path: '/film-lineup'
      fullPath: '/film-lineup'
      preLoaderRoute: typeof FilmLineupImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/film-lineup': typeof FilmLineupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/film-lineup': typeof FilmLineupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/film-lineup': typeof FilmLineupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/film-lineup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/film-lineup'
  id: '__root__' | '/' | '/film-lineup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmLineupRoute: typeof FilmLineupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmLineupRoute: FilmLineupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/film-lineup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/film-lineup": {
      "filePath": "film-lineup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
